spring:
  shardingsphere:
    datasource:
      names: master,slave
      #主库
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3301/client?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
        username: test
        password: 123456
      #从库
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3302/client?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
        username: test
        password: 123456

      #读写分离
    masterslave:
      # 读写分离配置
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    #打印sql
    props:
      sql.show: true