#################################### common config : ####################################
spring:
  application:
        name: springboot-admin
# Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        server-addr: 192.168.36.129:8848 # Nacos 服务器地址
  mail:
    host: smtp.163.com
    username: 18655377896@163.com
    password: 032502ds@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
       notify:
         mail:
            from: 18655377896@163.com
            to: 839192075@qq.com
  #安全认证
#  security:
#    user:
#      name: admin
#      password: admin

# 应用服务web访问端口
server:
  port: 8005
    # 下面是配置undertow作为服务器的参数
  undertow:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io-threads: 4
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker-threads: 20
      # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
      # 每块buffer的空间大小,越小的空间被利用越充分
      buffer-size: 1024
      # 是否分配的直接内存
      direct-buffers: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

  health:
    db:
      enabled: false
    mail:
      enabled: false
    redis:
      enabled: false
    mongo:
      enabled: false

